#!/bin/bash

# Generate the build script

xsltproc -v -o build templates/build.xsl data/_pages.xml;

# Create the README file

xsltproc -v -o ../README.md templates/readme.xsl data/_pages.xml;

# These commands will process HTML files with XSLT when you run `./build` inside the `src` directory.
# This list is dynamically generated as you add more pages to the `data/_pages.xml` file.

xsltproc -v -o ../public/index.html views/index.xsl data/index.xml;
xsltproc -v -o ../public/about/index.html views/about.xsl data/about.xml;
xsltproc -v -o ../public/team/index.html views/team.xsl data/team.xml;
xsltproc -v -o ../public/work/index.html views/work.xsl data/work.xml;
xsltproc -v -o ../public/process/index.html views/process.xsl data/process.xml;
xsltproc -v -o ../public/blog/index.html views/blog.xsl data/blog.xml;
xsltproc -v -o ../public/contact/index.html views/contact.xsl data/contact.xml;
