#!/bin/bash

# Generate the build script

xsltproc -v -o build templates/build.xsl data/_pages.xml;

# Create the README file

xsltproc -v -o ../README.md templates/readme.xsl data/_pages.xml;

# These commands will process HTML files with XSLT when you run `./build` inside the `src` directory.
# This list is dynamically generated as you add more pages to the `data/_pages.xml` file.

xsltproc -v -o ../public/index.html views/index.xsl data/index.xml;
xsltproc -v -o ../public/news/index.html views/news.xsl data/news.xml;
xsltproc -v -o ../public/events/index.html views/events.xsl data/events.xml;
xsltproc -v -o ../public/services/index.html views/services.xsl data/services.xml;
xsltproc -v -o ../public/about/index.html views/about.xsl data/about.xml;
xsltproc -v -o ../public/contact/index.html views/contact.xsl data/contact.xml;
